# To encrypt password:
# mvn jasypt:encrypt-value -Djasypt.encryptor.password=default-key -Djasypt.plugin.value=changeit

#
#

server:
  port: 7777
  ssl:
    enabled: false
    key-store-type: PKCS12
#    key-store: G:\dev\conf\XuComputer.pfx
#    Note: there must not be no space in "classpath:XuComputer.pfx"
    key-store: "classpath:XuComputer.pfx"
    key-store-password: ENC(kmSHM5NdF1QIAuNb+7KHgIs/nYJgEECReX+71096KGKfEcxTXAAONI/mOU/hGiN+)
    
logging:
  level:
    org.springframework: INFO
log.path: "/opt/app/logs"

management.endpoints.web.exposure.include: "*"

# Needed for swagger 2 to work with Spring boot 2.6
spring.mvc.pathmatch.matching-strategy: ant_path_matcher
server.servlet.context-path: /spring-boot-demo
