apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springboot-demo
  name: springboot-demo
spec:
  ports:
  - port: 7779
    protocol: TCP
    targetPort: 7777
  selector:
    app: springboot-demo